### ISSUE TITLE
Events Showing Time of Day Prefix

### ISSUE THREAD

**Issue by ChrisMarinos** [Symphono/wfh-slack-command#6]
![image](https://user-images.githubusercontent.com/182567/26886656-f6c8c74e-4b73-11e7-9902-24964e600c0b.png)

It looks like events are being created with a prefix of (12:00 am) for the time zone that the user is in. I suspect that this is because they're being created as events that span from 12am on one day to 12am on the next day rather than an "all day" event. I created a test event in the attached image and made it a 12am-12am event instead of an "all day" event, and it had the same formatting. I suspect that there is a different API or syntax in the calendar API that would yield the proper "all day" formatting.

**Comment by MarkLeMerise** [comment]
This should be fixed with PR #9
